services:
  redis:
    build:
      context: ../../..
      dockerfile: configs/docker/redis/Dockerfile
      args:
        USERNAME: devuser
        UID: 1000
        GID: 1000
    image: dev-redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped

    ports:
      - "2401:22"
      - "6379:6379"

    env_file:
      - ../../../env-files/redis.env

    volumes:
      - redis_data:/data

    networks:
      - dev-net

networks:
  dev-net:
    external: true

volumes:
  redis_data:
