services:
  rust-dev:
    build:
      context: ../../..
      dockerfile: configs/docker/base-dev.Dockerfile
      args:
        USERNAME: devuser
        UID: 1000
        GID: 1000
        PUBLIC_KEYS_DIR: /public-ssh-keys
    image: dev-rust:latest
    container_name: rust-dev
    hostname: rust-dev
    restart: unless-stopped
    command: sh -c "su devuser -c 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y' && /usr/sbin/sshd -D"

    ports:
      - "2201:22"

    volumes:
      - ../../../projects/rust:/home/devuser/workspace
      - ../../../logs/app-logs:/logs
      - ../../../public-ssh-keys:/public-ssh-keys:ro

    env_file:
      - ../../../env-files/rust.env

    networks:
      - dev-net

networks:
  dev-net:
    external: true

