services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: dev-mongodb:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped

    ports:
      - "2402:22"
      - "27017:27017"

    env_file:
      - ../../../env-files/mongodb.env

    volumes:
      - ../../../data/mongodb:/data/db

    networks:
      - dev-net

networks:
  dev-net:
    external: true
