services:
  mongodb:
    build:
      context: ../../..
      dockerfile: configs/docker/mongodb/Dockerfile
      args:
        USERNAME: devuser
        UID: 1000
        GID: 1000
        PUBLIC_KEYS_DIR: /public-ssh-keys
    image: dev-mongodb:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped

    ports:
      - "2402:22"
      - "27017:27017"

    env_file:
      - ../../../env-files/mongodb.env

    volumes:
      - ../../../data/mongodb:/data/db
      - ../../../public-ssh-keys:/public-ssh-keys:ro

    networks:
      - dev-net

networks:
  dev-net:
    external: true
