services:
  nginx:
    build:
      context: ../../..
      dockerfile: configs/docker/nginx/Dockerfile
      args:
        USERNAME: devuser
        UID: 1000
        GID: 1000
        PUBLIC_KEYS_DIR: /public-ssh-keys
    image: dev-nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped

    ports:
      - "2303:22"
      - "80:80"
      - "443:443"

    env_file:
      - ../../../env-files/nginx.env

    volumes:
      - ../../../configs/nginx:/etc/nginx/conf.d:ro
      - ../../../logs/nginx:/var/log/nginx
      - ../../../public-ssh-keys:/public-ssh-keys:ro

    networks:
      - dev-net

networks:
  dev-net:
    external: true
